### ISSUE TITLE
Is the blank line after HTTP version line necessary?

### ISSUE THREAD

**Issue by justin-calleja** [harttle/echo.js#1]
Hi,

Is the blank line after `GET / HTTP/1.1` necessary according to spec?

```
GET / HTTP/1.1

Host: localhost:8061
User-Agent: curl/7.54.0
Accept: */*
```

Thanks

P.S would you consider a PR to have an endpoint which shuts the echo server down?

I just built a similar module to test an HTTP client and then found this module. I think the shutdown feature is all that's missing here.

**Comment by harttle** [comment]
Glad to know that someone find it useful. And it’s great to have your feature.
As for that blank line, I do think that way. But I’ll look into the spec and make sure to respond with the raw request text

**Comment by justin-calleja** [comment]
Thanks! I'll look at implementing the endpoint sometime tomorrow :)

Nice weekend

**Comment by justin-calleja** [comment]
The statusLine and headers and now configurable via options.

**Comment by harttle** [comment]
> Both types of message consist of a start-line, zero or more header fields (also known as "headers"), an empty line (i.e., a line with nothing preceding the CRLF) indicating the end of the header fields, and possibly a message-body. --[http/1.1](https://tools.ietf.org/html/rfc2616#section-4.1)

The blank line after request-line is not conformance, and that line break should be CRLF. Should we print the raw request text? At least we can remove that empty line after request-line.

**Comment by justin-calleja** [comment]
I had removed the blank line after the request-line (or statusLine) - but it can be overwritten by user if desired.

To overwrite:

```js
var echojs = require('echo.js');

var server = echojs.createServer({
  statusLine: req => req.method + ' ' + req.url + ' HTTP/' + req.httpVersion + '\r\n';
});
```

Note the addition of '\r\n' at the end. Currently, there's a hardcoded '\n' between the `statusLine` and `headers`. There's also a hardcoded one after the headers and the headers all end with a '\n'.

I can change all those to '\r\n'. Should I just commit to master or do you prefer another approach? (committing to a dev branch and PRing)?
