### ISSUE TITLE
Make POST /shutdown endpoint optional / configurable

### ISSUE THREAD

**Issue by justin-calleja** [harttle/echo.js#9]
One can always use the following (instead of making a POST to /shutdown), to close the echo server:

```js
const server = createServer();

server.close();
```

**Comment by harttle** [comment]
You're right. We can shutdown it view HTTP, but we cannot start it. This feature is somehow wield if enabled by default.
It's handy to start/stop it programmatically when creating test stubs. In this point of view, POST /shutdown will not be preferred.

**Comment by justin-calleja** [comment]
@harttle thanks for the feedback! (need to start paying attention to notifications in Github - almost missed this).

I have gone ahead and made a PR with a proposed solution. See what you think and we can change it if you think there's a better way.

Well, actually, the solution was already there: to use `server.close()`. I just added a way to add back the POST /shutdown or anything else the user might want to do after `res.end()` - they can pass an `onResponseEndCb` function which receives the `req` and `server`.

谢谢
